In [32]:
from rtbm.riemann_theta.riemann_theta import RiemannTheta

import pandas as pd
import numpy as np

from sklearn import linear_model
from sklearn.metrics import confusion_matrix, classification_report


import time

In [2]:
# Load MNIST dataset
MNIST_train = pd.read_csv('~/data/mnist_train.csv', delimiter=",",header=None).values
MNIST_test  = pd.read_csv('~/data/mnist_test.csv', delimiter=",",header=None).values

# Prepare data (normalized onto [0,1])
Y_train = MNIST_train[0:10000,0]
X_train = MNIST_train[0:10000,1:]/255.0

Y_test = MNIST_test[:,0]
X_test = MNIST_test[:,1:]/255.0

In [68]:
# Keras fit
import theano

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Dropout, Reshape  
from keras.callbacks import EarlyStopping
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import SGD


model = Sequential() 
#model.add(Reshape((1, Xtrain.shape[1], Xtrain.shape[2]), input_shape=(Xtrain.shape[1], Xtrain.shape[2])))

model.add(Dense(10,  input_dim=784))
model.add(Activation('linear'))
model.add(Dense(output_dim=1))
model.add(Activation('softmax'))              

sgd = SGD(lr=1)

tic = time.clock()

model.compile(loss='mse', optimizer=sgd)

toc = time.clock()

print("Compile time: ",toc-tic)

tic = time.clock()

model.fit(X_train, Y_train, batch_size=1000, nb_epoch=100, validation_data=None, shuffle=False, verbose=1)  
toc = time.clock()

preds = model.predict(X_test)

print("Run time: ",toc-tic)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`
  app.launch_new_instance()


('Compile time: ', 0.003985000000056971)
Epoch 1/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 2/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 3/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 4/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 5/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 6/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 7/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 8/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 9/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 10/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466
Epoch 11/100
10000/10000 [==============================] - 0s 4us/step - loss: 20.1466


KeyboardInterrupt: 

In [64]:
np.abs(np.round(preds.flatten()))


array([6., 3., 2., ..., 8., 5., 5.], dtype=float32)

In [65]:
P=np.abs(np.round(preds.flatten()))


print(classification_report(Y_train,P.T))
print(confusion_matrix(Y_train, P.T))

             precision    recall  f1-score   support

        0.0       0.16      0.03      0.05      1001
        1.0       0.12      0.07      0.08      1127
        2.0       0.10      0.13      0.11       991
        3.0       0.10      0.11      0.10      1032
        4.0       0.11      0.14      0.12       980
        5.0       0.09      0.15      0.11       863
        6.0       0.10      0.14      0.11      1014
        7.0       0.12      0.14      0.13      1070
        8.0       0.10      0.08      0.09       944
        9.0       0.08      0.02      0.03       978
       10.0       0.00      0.00      0.00         0
       11.0       0.00      0.00      0.00         0
       12.0       0.00      0.00      0.00         0

avg / total       0.11      0.10      0.09     10000

[[ 30  41 146 125 119 147 144 128  84  28   8   1   0]
 [ 11  74 143 140 166 164 162 157  78  24   8   0   0]
 [ 22  63 129 111 116 149 151 120  84  35   8   3   0]
 [ 25  65 140 113 116 176 154 125  83